FROM node:20

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci --include=dev

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
